wandb_version: 1

batch_size:
  desc: null
  value: 64
cr:
  desc: null
  value: 10
data_root:
  desc: null
  value: /content/drive/My Drive/Work/data/mnist
epochs:
  desc: null
  value: 13
img_dim:
  desc: null
  value: 784
lr:
  desc: null
  value: 0.0005
ngpu:
  desc: null
  value: 1
num_workers:
  desc: null
  value: 2
optimizer:
  desc: null
  value: adam
z_dim:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691220807.816243
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.9.12
      5: 0.15.8
      8:
      - 5
