wandb_version: 1

batch_size:
  value: 64
cr:
  value: 70
data_root:
  value: /content/drive/My Drive/Work/data/mnist
epochs:
  value: 58
img_dim:
  value: 784
lr:
  value: 0.05
ngpu:
  value: 1
num_workers:
  value: 2
optimizer:
  value: adam
z_dim:
  value: 100
