wandb_version: 1

batch_size:
  value: 16
cr:
  value: 50
data_root:
  value: /content/drive/My Drive/Work/data/mnist
epochs:
  value: 28
img_dim:
  value: 784
lr:
  value: 0.001
ngpu:
  value: 1
num_workers:
  value: 2
optimizer:
  value: adam
z_dim:
  value: 100
