wandb_version: 1

TV_beta:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 2
cr:
  desc: null
  value: 10
pic_width:
  desc: null
  value: 28
weight_decay:
  desc: null
  value: 1.0e-07
z_dim:
  desc: null
  value: 256
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708860625.002987
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 2
      - 23
      - 37
      4: 3.10.9
      5: 0.15.5
      8:
      - 5
